export const ML_TOOLS = [
  {
    id: 'weight-predictor',
    name: 'Weight Predictor',
    description: 'Predict body weight from length, species, age group, and sex using regression.',
    icon: '⚖️',
    category: 'Regression',
    badgeColor: 'blue',
    endpoint: '/api/ml/weight-predictor',
    inputFields: [
      { id: 'species', label: 'Species', type: 'select', options: ['Saltwater Crocodile', 'Nile Crocodile', 'American Alligator', 'Mugger Crocodile', 'Gharial'], required: true },
      { id: 'length', label: 'Body Length (cm)', type: 'number', placeholder: '380', min: 50, max: 700, required: true },
      { id: 'sex', label: 'Sex', type: 'select', options: ['Male', 'Female'], required: true },
      { id: 'ageGroup', label: 'Age Group', type: 'select', options: ['Juvenile', 'Sub-adult', 'Adult', 'Senior'], required: true },
      { id: 'region', label: 'Region', type: 'select', options: ['Southeast Asia', 'Africa', 'North America', 'Australia', 'South America'], required: true },
    ],
    resultConfig: { type: 'single-value', unit: 'kg', label: 'Predicted Weight', description: 'Estimated body weight based on your inputs.' },
    mockResult: { value: 487, unit: 'kg', confidence: [420, 550], label: 'Predicted Weight' },
  },
  {
    id: 'age-classifier',
    name: 'Age Classifier',
    description: 'Classify age group from physical traits using a classification model.',
    icon: '🦎',
    category: 'Classification',
    badgeColor: 'green',
    endpoint: '/api/ml/age-classifier',
    inputFields: [
      { id: 'species', label: 'Species', type: 'select', options: ['Saltwater Crocodile', 'Nile Crocodile', 'American Alligator', 'Mugger Crocodile'], required: true },
      { id: 'length', label: 'Body Length (cm)', type: 'number', placeholder: '250', min: 30, max: 700, required: true },
      { id: 'weight', label: 'Body Weight (kg)', type: 'number', placeholder: '150', min: 1, max: 1200, required: true },
      { id: 'toothWear', label: 'Tooth Wear', type: 'select', options: ['Low', 'Medium', 'High'], required: true },
      { id: 'scalePattern', label: 'Scale Pattern', type: 'select', options: ['Uniform', 'Banded', 'Spotted', 'Mixed'], required: true },
    ],
    resultConfig: { type: 'classification', label: 'Predicted Age Group', description: 'Age group classification with probability breakdown.' },
    mockResult: { label: 'Adult', probabilities: [{ group: 'Juvenile', prob: 0.04 }, { group: 'Sub-adult', prob: 0.12 }, { group: 'Adult', prob: 0.76 }, { group: 'Senior', prob: 0.08 }] },
  },
  {
    id: 'conservation-predictor',
    name: 'Conservation Status Predictor',
    description: 'Predict IUCN conservation status from population size, habitat loss, and threat factors.',
    icon: '🌿',
    category: 'Classification',
    badgeColor: 'green',
    endpoint: '/api/ml/conservation-predictor',
    inputFields: [
      { id: 'species', label: 'Species', type: 'select', options: ['Saltwater Crocodile', 'Nile Crocodile', 'American Alligator', 'Mugger Crocodile', 'Gharial'], required: true },
      { id: 'population', label: 'Population Size', type: 'number', placeholder: '5000', min: 1, required: true },
      { id: 'habitatLoss', label: 'Habitat Loss (%)', type: 'slider', min: 0, max: 100, defaultValue: 30 },
      { id: 'huntingPressure', label: 'Hunting Pressure', type: 'select', options: ['None', 'Low', 'Medium', 'High'], required: true },
      { id: 'captiveBreeding', label: 'Captive Breeding Program', type: 'toggle' },
      { id: 'climateThreat', label: 'Climate Threat Level', type: 'select', options: ['Low', 'Medium', 'High', 'Severe'], required: true },
    ],
    resultConfig: { type: 'classification', label: 'Predicted IUCN Status', description: 'Predicted conservation status with contributing risk factors.' },
    mockResult: { label: 'Vulnerable', probabilities: [{ group: 'Least Concern', prob: 0.08 }, { group: 'Near Threatened', prob: 0.15 }, { group: 'Vulnerable', prob: 0.52 }, { group: 'Endangered', prob: 0.25 }] },
  },
  {
    id: 'habitat-suitability',
    name: 'Habitat Suitability',
    description: 'Score habitat suitability based on climate, geography, and human activity factors.',
    icon: '🗺️',
    category: 'Score',
    badgeColor: 'amber',
    endpoint: '/api/ml/habitat-suitability',
    inputFields: [
      { id: 'region', label: 'Region', type: 'select', options: ['Southeast Asia', 'Sub-Saharan Africa', 'North America', 'Australia', 'South America'], required: true },
      { id: 'avgTemp', label: 'Avg Temperature (°C)', type: 'number', placeholder: '28', min: 5, max: 45, required: true },
      { id: 'rainfall', label: 'Annual Rainfall (mm)', type: 'number', placeholder: '1800', min: 100, required: true },
      { id: 'waterProximity', label: 'Water Body Proximity (km)', type: 'number', placeholder: '2', min: 0, required: true },
      { id: 'humanActivity', label: 'Human Activity Index', type: 'slider', min: 0, max: 10, defaultValue: 4 },
      { id: 'vegetation', label: 'Vegetation Density', type: 'select', options: ['Sparse', 'Moderate', 'Dense', 'Very Dense'], required: true },
    ],
    resultConfig: { type: 'score', label: 'Habitat Suitability Score', description: 'Score from 0–100 indicating how suitable this habitat is.' },
    mockResult: { score: 74, label: 'Good', breakdown: ['Strong water proximity', 'Adequate temperature', 'Moderate human pressure'] },
  },
  {
    id: 'observation-trend',
    name: 'Observation Trend Analysis',
    description: 'Analyze and predict observation trends over time for a species in a region.',
    icon: '📈',
    category: 'Time Series',
    badgeColor: 'purple',
    endpoint: '/api/ml/observation-trend',
    inputFields: [
      { id: 'species', label: 'Species', type: 'select', options: ['Saltwater Crocodile', 'Nile Crocodile', 'American Alligator', 'Gharial'], required: true },
      { id: 'region', label: 'Region', type: 'select', options: ['Southeast Asia', 'Sub-Saharan Africa', 'North America', 'Australia'], required: true },
      { id: 'startYear', label: 'Start Year', type: 'number', placeholder: '2015', min: 2000, max: 2024, required: true },
      { id: 'endYear', label: 'End Year', type: 'number', placeholder: '2024', min: 2000, max: 2030, required: true },
      { id: 'observationType', label: 'Observation Type', type: 'select', options: ['Sighting', 'Camera Trap', 'Survey'], required: true },
    ],
    resultConfig: { type: 'chart', label: 'Observation Trend', description: 'Predicted trend line based on historical patterns.' },
    mockResult: { trend: 'Increasing', data: [{ year: 2015, count: 120 }, { year: 2016, count: 135 }, { year: 2017, count: 142 }, { year: 2018, count: 160 }, { year: 2019, count: 178 }, { year: 2020, count: 165 }, { year: 2021, count: 195 }, { year: 2022, count: 210 }, { year: 2023, count: 225 }, { year: 2024, count: 240 }] },
  },
  {
    id: 'population-risk',
    name: 'Population Risk Score',
    description: 'Generate a 0–100 risk score based on population, habitat, and genetic factors.',
    icon: '⚠️',
    category: 'Score',
    badgeColor: 'red',
    endpoint: '/api/ml/population-risk',
    inputFields: [
      { id: 'species', label: 'Species', type: 'select', options: ['Saltwater Crocodile', 'Nile Crocodile', 'American Alligator', 'Gharial', 'Chinese Alligator'], required: true },
      { id: 'population', label: 'Current Population', type: 'number', placeholder: '5000', min: 1, required: true },
      { id: 'habitatSize', label: 'Habitat Size (km²)', type: 'number', placeholder: '2000', min: 1, required: true },
      { id: 'geneticDiversity', label: 'Genetic Diversity Index', type: 'slider', min: 0, max: 1, defaultValue: 0.5, step: 0.01 },
      { id: 'predationPressure', label: 'Predation Pressure', type: 'select', options: ['None', 'Low', 'Medium', 'High'], required: true },
      { id: 'diseasePrevalence', label: 'Disease Prevalence', type: 'select', options: ['None', 'Low', 'Medium', 'High'], required: true },
    ],
    resultConfig: { type: 'score', label: 'Population Risk Score', description: 'Risk score from 0 (safe) to 100 (critical).' },
    mockResult: { score: 62, label: 'High Risk', breakdown: ['Low genetic diversity', 'Shrinking habitat', 'Moderate predation'] },
  },
  {
    id: 'species-identifier',
    name: 'Species Identifier',
    description: 'Identify the most likely crocodilian species from physical feature inputs.',
    icon: '🔍',
    category: 'Classification',
    badgeColor: 'green',
    endpoint: '/api/ml/species-identifier',
    inputFields: [
      { id: 'length', label: 'Body Length (cm)', type: 'number', placeholder: '300', min: 30, max: 700, required: true },
      { id: 'snoutShape', label: 'Snout Shape', type: 'select', options: ['Broad V-shape', 'Narrow V-shape', 'U-shape', 'Elongated'], required: true },
      { id: 'scaleColor', label: 'Scale Color', type: 'select', options: ['Dark Grey', 'Olive Green', 'Brown', 'Black', 'Yellow-Green'], required: true },
      { id: 'region', label: 'Geographic Region', type: 'select', options: ['Southeast Asia', 'Africa', 'North America', 'South America', 'Australia'], required: true },
      { id: 'habitat', label: 'Habitat Type', type: 'select', options: ['Freshwater', 'Saltwater', 'Brackish'], required: true },
      { id: 'bellyScales', label: 'Belly Scale Count', type: 'number', placeholder: '28', min: 10, max: 50, required: true },
    ],
    resultConfig: { type: 'classification', label: 'Top Species Matches', description: 'Most likely species based on physical characteristics.' },
    mockResult: { label: 'Crocodylus porosus', probabilities: [{ group: 'Saltwater Crocodile', prob: 0.82 }, { group: 'Nile Crocodile', prob: 0.11 }, { group: 'American Alligator', prob: 0.07 }] },
  },
]