export const ML_TOOLS = [
  {
    id: 'weight-predictor',
    name: 'Weight Predictor',
    description: 'Predict body weight from length, species, age, and sex using regression.',
    icon: '⚖️',
    endpoint: '/api/ml/weight',
    inputFields: [
      { name: 'length', label: 'Length (m)', type: 'number', placeholder: '4.2' },
      { name: 'species', label: 'Species', type: 'select', options: ['Crocodylus porosus', 'Crocodylus niloticus', 'Alligator mississippiensis'] },
      { name: 'age', label: 'Age (years)', type: 'number', placeholder: '15' },
      { name: 'sex', label: 'Sex', type: 'select', options: ['Male', 'Female'] },
    ],
  },
  {
    id: 'age-classifier',
    name: 'Age Classifier',
    description: 'Classify age group from physical traits using a classification model.',
    icon: '🦎',
    endpoint: '/api/ml/age',
    inputFields: [
      { name: 'length', label: 'Length (m)', type: 'number', placeholder: '3.5' },
      { name: 'weight', label: 'Weight (kg)', type: 'number', placeholder: '200' },
      { name: 'species', label: 'Species', type: 'select', options: ['Crocodylus porosus', 'Crocodylus niloticus', 'Alligator mississippiensis'] },
    ],
  },
  {
    id: 'conservation-predictor',
    name: 'Conservation Status Predictor',
    description: 'Predict IUCN conservation status from population and habitat data.',
    icon: '🌿',
    endpoint: '/api/ml/conservation',
    inputFields: [
      { name: 'population', label: 'Est. Population', type: 'number', placeholder: '100000' },
      { name: 'habitatScore', label: 'Habitat Score (0–10)', type: 'number', placeholder: '7' },
      { name: 'threatLevel', label: 'Threat Level', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
    ],
  },
  {
    id: 'habitat-suitability',
    name: 'Habitat Suitability',
    description: 'Score habitat suitability based on climate and geographic factors.',
    icon: '🗺️',
    endpoint: '/api/ml/habitat',
    inputFields: [
      { name: 'region', label: 'Region', type: 'select', options: ['Southeast Asia', 'Sub-Saharan Africa', 'North America', 'Australia', 'South America'] },
      { name: 'avgTemp', label: 'Avg Temperature (°C)', type: 'number', placeholder: '28' },
      { name: 'waterProximity', label: 'Water Proximity (km)', type: 'number', placeholder: '2' },
    ],
  },
  {
    id: 'observation-trend',
    name: 'Observation Trend Analysis',
    description: 'Analyze observation trends over time for a given species and region.',
    icon: '📈',
    endpoint: '/api/ml/trend',
    inputFields: [
      { name: 'species', label: 'Species', type: 'select', options: ['Crocodylus porosus', 'Crocodylus niloticus', 'Alligator mississippiensis'] },
      { name: 'region', label: 'Region', type: 'select', options: ['Southeast Asia', 'Sub-Saharan Africa', 'North America', 'Australia'] },
      { name: 'startYear', label: 'Start Year', type: 'number', placeholder: '2010' },
      { name: 'endYear', label: 'End Year', type: 'number', placeholder: '2024' },
    ],
  },
  {
    id: 'population-risk',
    name: 'Population Risk Score',
    description: 'Generate a 0–100 risk score based on multiple population factors.',
    icon: '⚠️',
    endpoint: '/api/ml/risk',
    inputFields: [
      { name: 'population', label: 'Est. Population', type: 'number', placeholder: '5000' },
      { name: 'growthRate', label: 'Growth Rate (%)', type: 'number', placeholder: '-2.5' },
      { name: 'habitatLoss', label: 'Habitat Loss (%)', type: 'number', placeholder: '30' },
      { name: 'huntingPressure', label: 'Hunting Pressure', type: 'select', options: ['None', 'Low', 'Medium', 'High'] },
    ],
  },
  {
    id: 'species-identifier',
    name: 'Species Identifier',
    description: 'Identify species from physical feature inputs.',
    icon: '🔍',
    endpoint: '/api/ml/identify',
    inputFields: [
      { name: 'snoutShape', label: 'Snout Shape', type: 'select', options: ['Broad V-shape', 'Narrow V-shape', 'U-shape', 'Elongated'] },
      { name: 'scalePattern', label: 'Scale Pattern', type: 'select', options: ['Uniform', 'Banded', 'Spotted', 'Mixed'] },
      { name: 'region', label: 'Native Region', type: 'select', options: ['Southeast Asia', 'Africa', 'Americas', 'Australia'] },
      { name: 'length', label: 'Approx Length (m)', type: 'number', placeholder: '3.0' },
    ],
  },
]